version: "3.9"

services:
  web:
    container_name: stock_web
    build: .
    command: /wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - stock_backend

  db:
    image: mariadb:10.5
    container_name: stock_mariadb_10_5
    restart: always
    environment:
      MYSQL_DATABASE: gestock
      MYSQL_USER: efrita
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - stock_mariadb_data:/var/lib/mysql
    networks:
      - stock_backend

networks:
  stock_backend:
    name: stock_backend

volumes:
  stock_mariadb_data:
    name: stock_mariadb_data
