# Generated by Django 5.2.1 on 2025-05-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock bajo'), ('STOCK_NEGATIVO', 'Stock negativo'), ('SIN_CATEGORIA', 'Producto sin categoría'), ('VENCIMIENTO', 'Producto por vencer')], max_length=30)),
                ('referencia', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False)),
            ],
        ),
    ]
