# Generated by Django 5.2.1 on 2025-06-02 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_almacen_options_alter_empresa_options_and_more'),
        ('stock', '0003_movimientostock_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertasistema',
            old_name='referencia',
            new_name='resumen',
        ),
        migrations.RemoveField(
            model_name='alertasistema',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='acciones_sugeridas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.almacen'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='canal_notificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.movimientostock'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.producto'),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='usuario_resolutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL),
        ),
    ]
