# Generated by Django 5.2.1 on 2025-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_referencia_alertasistema_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='General', max_length=100, unique=True),
        ),
    ]
