# Generated by Django 4.2.10 on 2025-06-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rol",
            options={
                "default_permissions": (),
                "permissions": [
                    ("view_rol", "Ver lista de roles"),
                    ("add_rol", "Crear nuevo rol"),
                    ("change_rol", "Modificar rol existente"),
                    ("delete_rol", "Eliminar rol"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "default_permissions": (),
                "permissions": [
                    ("view_usuario", "Ver lista de usuarios"),
                    ("add_usuario", "Crear usuario"),
                    ("change_usuario", "Modificar usuario"),
                    ("delete_usuario", "Eliminar usuario"),
                ],
            },
        ),
    ]
