# Generated by Django 5.2.1 on 2025-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Juan', max_length=100)),
                ('apellido', models.CharField(default='Pérez', max_length=100)),
                ('dni', models.CharField(default='00000000', max_length=10, unique=True)),
                ('telefono', models.CharField(default='0000000000', max_length=20)),
                ('email', models.EmailField(default='cliente@ejemplo.com', max_length=254)),
                ('direccion', models.CharField(default='Sin dirección', max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
